In [17]:
 import pandas as pd
from sklearn.tree import DecisionTreeClassifier
#to split dataset into test and train dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
music_data=pd.read_csv('music.csv')
music_data


#we don't have null values in dataset and duplicacy of data is also not present in this data
#but to train a model we have to separate this dataset into output and input dataset

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [82]:
#genre is output dataset we have to make prediction which age group likes which genre of music on the basis of this data
#once we train our model we can give a new input dataset to predict given age of person and gender which genre of music he/she likes.
#put cursor on method name to get signature press shift+tab
x=music_data.drop(columns=['genre'])
#drop doesn't modify original dataset it only separtes to give new column

y=music_data['genre']
#allocating size of test dataset
#measure accuracy ofmodel
#dividing into train set 70% and test set 30%
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [84]:
model=DecisionTreeClassifier()
#ctrl+enter to directly run section
#measure accuracy ofmodel
#dividing into train set 70% and test set 30%
#pass only train set
model.fit(x_train,y_train)
#model.fit(x,y) #this passes entire dataset
music_data
#predictions=model.predict([[21,1],[30,0]]) 
predictions=model.predict(x_test)
#predictions
#accuracy score gives score from 0 to 1 to give accuracy of model
score=accuracy_score(y_test,predictions)
score

1.0